name: insiders

on:
  repository_dispatch:
  schedule:
  - cron: '5 12 * * 0'

jobs:
  insiders:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: python -m pip install httpx
    - name: Grant/revoke access
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: python insiders.py
    - name: Commit changes
      run: |
        git config --global user.name "Timothée Mazzucotelli"
        git config --global user.email "pawamoy@users.noreply.github.com"
        git commit -am "CI: Update JSON data" && git push
